
#module Minc2IO

# using libminc_jll
# include("LibMinc.jl")           # generated by Clang.jl from minc2_simple.h
# using .LibMinc
using CEnum: CEnum, @cenum

# -------------------- Enums and type maps --------------------

@cenum DIM::UInt32 begin
    DIM_UNKNOWN = Cint(MINC2_DIM_UNKNOWN)
    DIM_X       = Cint(MINC2_DIM_X)
    DIM_Y       = Cint(MINC2_DIM_Y)
    DIM_Z       = Cint(MINC2_DIM_Z)
    DIM_TIME    = Cint(MINC2_DIM_TIME)
    DIM_VEC     = Cint(MINC2_DIM_VEC)
    DIM_END     = Cint(MINC2_DIM_END)
end

minc2_spatial = Dict(DIM_X => 1, DIM_Y => 2, DIM_Z => 3)

julia_to_minc2 = Dict(
    Type{Int8}     => Cint(MINC2_BYTE ),
    Type{Int16}    => Cint(MINC2_SHORT),
    Type{Int32}    => Cint(MINC2_INT ),
    #Type{Int64}    => Cint(MINC2_LONG ),
    Type{Float32}  => Cint(MINC2_FLOAT ),
    Type{Float64}  => Cint(MINC2_DOUBLE ),
    Type{String}   => Cint(MINC2_STRING ),
    Type{UInt8}    => Cint(MINC2_UBYTE ),
    Type{UInt16}   => Cint(MINC2_USHORT ),
    Type{UInt32}   => Cint(MINC2_UINT ),
    #Type{UInt64}   => Cint(MINC2_ULONG ),
    Type{Complex{Int16}} => Cint(MINC2_SCOMPLEX ),
    Type{Complex{Int32}} => Cint(MINC2_ICOMPLEX ),
    Type{Complex{Float32}} => Cint(MINC2_FCOMPLEX ),
    Type{Complex{Float64}} => Cint(MINC2_DCOMPLEX ),
    Type{Any}      => Cint(MINC2_UNKNOWN),
)

minc2_to_julia = Dict(v => k for (k, v) in julia_to_minc2)

@cenum STATUS::Int32 begin
    SUCCESS = Cint(MINC2_SUCCESS)
    ERROR   = Cint(MINC2_ERROR)
end

struct Minc2Error <: Exception
    message::String
end

Base.showerror(io::IO, e::Minc2Error) = print(io, "MINC2:", e.message)

macro minc2_check(ex)
    :( $(esc(ex)) == MINC2_SUCCESS ? nothing : throw(Minc2Error("error")) )
end

# -------------------- Volume handle --------------------
mutable struct VolumeHandle
    x::minc2_file_handle

    function VolumeHandle()
        h = minc2_allocate0()
        obj = new(h)
        finalizer(obj) do v
            if v.x != C_NULL
                minc2_destroy(v.x)
                v.x = C_NULL
            end
        end
        obj
    end
end

# -------------------- Header struct --------------------

mutable struct MincHeader
    dims::Vector{Int32}
    start::Vector{Float64}
    step::Vector{Float64}
    dir_cos::Matrix{Float64}
    dir_cos_valid::Vector{Bool}
    axis::Vector{DIM}
    irregular::Vector{Bool}
    offsets::Vector{Union{Vector{Float64},Nothing}}
    widths::Vector{Union{Vector{Float64},Nothing}}

    function MincHeader(ndim::Integer)
        new(
            zeros(Int32, ndim),
            zeros(Float64, ndim),
            ones(Float64, ndim),
            Matrix{Float64}(undef, ndim, 3),
            falses(ndim),
            fill(DIM_UNKNOWN, ndim),
            falses(ndim),
            Union{Vector{Float64},Nothing}[nothing for _ in 1:ndim],
            Union{Vector{Float64},Nothing}[nothing for _ in 1:ndim],
        )
    end
end

# -------------------- Basic I/O --------------------

function open_minc_file(fname::String)::VolumeHandle
    h = VolumeHandle()
    @minc2_check minc2_open(h.x, fname)
    return h
end

function define_minc_file(hdr::MincHeader,
                          ::Type{Store}=Float32,
                          ::Type{Repr}=Store) where {Store,Repr}
    h = VolumeHandle()
    store_type = julia_to_minc2[Type{Store}]
    repr_type  = julia_to_minc2[Type{Repr}]

    dims_vec = Vector{minc2_dimension}(undef, length(hdr.dims) + 1)
    for (i, len) in enumerate(hdr.dims)
        offsets_ptr = C_NULL
        widths_ptr = C_NULL
        if hdr.irregular[i] && hdr.offsets[i] !== nothing
            offsets_ptr = Base.unsafe_convert(Ptr{Cdouble}, hdr.offsets[i])
        end
        if hdr.irregular[i] && hdr.widths[i] !== nothing
            widths_ptr = Base.unsafe_convert(Ptr{Cdouble}, hdr.widths[i])
        end
        dims_vec[i] = minc2_dimension(
            hdr.axis[i],
            len,
            hdr.irregular[i] ? 1 : 0,
            hdr.step[i],
            hdr.start[i],
            hdr.dir_cos_valid[i] ? 1 : 0,
            (hdr.dir_cos[i,1], hdr.dir_cos[i,2], hdr.dir_cos[i,3]),
            offsets_ptr,
            widths_ptr,
        )
    end
    dims_vec[end] = minc2_dimension(
        Cint(MINC2_DIM_END), 0, 0, 0.0, 0.0, 0, (0.0, 0.0, 0.0), C_NULL, C_NULL
    )

    @minc2_check minc2_define(h.x, dims_vec, store_type, repr_type)

    global_scaling = 0
    slice_scaling  = 0
    if store_type != repr_type &&
       !(Store==Float32 && Repr==Float64 || Store==Float64 && Repr==Float32) &&
       !(Store==UInt8  && Repr==Int8   || Store==Int8   && Repr==UInt8) &&
       !(Store==UInt16 && Repr==Int16  || Store==Int16  && Repr==UInt16)
        global_scaling = 1
    end

    @minc2_check minc2_set_scaling(h.x, global_scaling, slice_scaling)
    return h
end

function create_minc_file(h::VolumeHandle, path::AbstractString)
    @minc2_check minc2_create(h.x, path)
    return nothing
end

function close_minc_file(h::VolumeHandle)
    @minc2_check minc2_close(h.x)
    return nothing
end

# -------------------- Introspection --------------------

function ndim(h::VolumeHandle)::Int
    dd = Ref{Cint}(0)
    @minc2_check minc2_ndim(h.x, dd)
    return dd[]
end

function store_type(h::VolumeHandle)::Type
    minc_dtype = Ref{Cint}(0)
    @minc2_check minc2_storage_data_type(h.x, minc_dtype)
    return minc2_to_julia[minc_dtype[]]
end

function representation_type(h::VolumeHandle)::Type
    minc_dtype = Ref{Cint}(0)
    @minc2_check minc2_data_type(h.x, minc_dtype)
    return minc2_to_julia[minc_dtype[]]
end

function setup_standard_order(h::VolumeHandle)
    @minc2_check minc2_setup_standard_order(h.x)
    return nothing
end

# -------------------- Header helpers --------------------

function _hdr_convert!(hdr::MincHeader, dd::Ref{Ptr{minc2_dimension}})::MincHeader
    dims_ptr = dd[]
    for i in 1:length(hdr.start)
        d = unsafe_load(dims_ptr, i)
        hdr.dims[i]   = d.length
        hdr.start[i]  = d.start
        hdr.step[i]   = d.step
        hdr.irregular[i] = d.irregular != 0

        if d.have_dir_cos != 0
            hdr.dir_cos[i, :] .= (d.dir_cos[1], d.dir_cos[2], d.dir_cos[3])
            hdr.dir_cos_valid[i] = true
        else
            hdr.dir_cos[i, :] .= 0.0
            if haskey(minc2_spatial, DIM(d.id))
                hdr.dir_cos[i, minc2_spatial[DIM(d.id)]] = 1.0
            end
            hdr.dir_cos_valid[i] = false
        end
        hdr.axis[i] = DIM(d.id)
        
        if hdr.irregular[i] && d.offsets != C_NULL
            hdr.offsets[i] = copy(unsafe_wrap(Array{Cdouble}, d.offsets, d.length))
        else
            hdr.offsets[i] = nothing
        end
        if hdr.irregular[i] && d.widths != C_NULL
            hdr.widths[i] = copy(unsafe_wrap(Array{Cdouble}, d.widths, d.length))
        else
            hdr.widths[i] = nothing
        end
    end
    return hdr
end

function representation_header(h::VolumeHandle)::MincHeader
    hdr = MincHeader(ndim(h))
    dd  = Ref{Ptr{minc2_dimension}}()
    @minc2_check minc2_get_representation_dimensions(h.x, dd)
    return _hdr_convert!(hdr, dd)
end

function store_header(h::VolumeHandle)::MincHeader
    hdr = MincHeader(ndim(h))
    dd  = Ref{Ptr{minc2_dimension}}()
    @minc2_check minc2_get_store_dimensions(h.x, dd)
    return _hdr_convert!(hdr, dd)
end

# -------------------- Volume allocation & loading --------------------

function empty_like_minc_volume_raw(h::VolumeHandle,
                                    ::Type{T}=Float32)::Tuple{Array{T},MincHeader} where T<:Number
    store_hdr = store_header(h)
    volume = Array{T}(undef, store_hdr.dims...)
    return volume, store_hdr
end

function minc2_load_and_convert_complete_volume(h::VolumeHandle,
                                                volume::Array{T},
                                                ::Type{T}) where T
    @minc2_check minc2_load_complete_volume(h.x,
        Base.unsafe_convert(Ptr{Cvoid}, volume),
        julia_to_minc2[Type{T}])
    return volume
end

function minc2_load_and_convert_complete_volume(h::VolumeHandle,
                                                volume::Array{Tin},
                                                ::Type{Tout}) where {Tin<:AbstractFloat,Tout<:Integer}
    @warn "Truncating volume data to integer type" Tin Tout
    @minc2_check minc2_load_complete_volume(h.x,
        Base.unsafe_convert(Ptr{Cvoid}, volume),
        julia_to_minc2[Type{Tin}])
    return trunc.(Tout, volume)
end

function minc2_load_and_convert_complete_volume(h::VolumeHandle,
        volume::Array{Tin},
        ::Type{Tout}) where {Tin<:Number,Tout<:Number}
    @minc2_check minc2_load_complete_volume(h.x,
        Base.unsafe_convert(Ptr{Cvoid}, volume),
        julia_to_minc2[Type{Tin}])
    return convert.(Tout, volume)
end

function read_minc_volume_raw(h::VolumeHandle,
        dtype::Type{T}=Float32)::Tuple{Array{T},MincHeader} where T<:Number
    fdtype = representation_type(h)
    volume, store_hdr = empty_like_minc_volume_raw(h, fdtype.parameters[1])
    return minc2_load_and_convert_complete_volume(h, volume, dtype), store_hdr
end

function empty_like_minc_volume_std(h::VolumeHandle,
        ::Type{T}=Float32)::Tuple{Array{T},MincHeader,MincHeader} where T<:Number
    setup_standard_order(h)
    store_hdr = store_header(h)
    hdr       = representation_header(h)
    volume    = Array{T}(undef, hdr.dims...)
    return volume, hdr, store_hdr
end

function read_minc_volume_std(h::VolumeHandle,
        dtype::Type{T}=Float32)::Tuple{Array{T},MincHeader,MincHeader} where T<:Number
    fdtype = representation_type(h)
    volume, hdr, store_hdr = empty_like_minc_volume_std(h, fdtype.parameters[1])
    return minc2_load_and_convert_complete_volume(h, volume, dtype), hdr, store_hdr
end

# Path-based helpers (open/close internally)

function empty_like_minc_volume_std(path::String,
                                    ::Type{T}=Float32)::Tuple{Array{T},MincHeader,MincHeader} where T<:Number
    handle = open_minc_file(path)
    volume, hdr, store_hdr = empty_like_minc_volume_std(handle, T)
    close_minc_file(handle)
    finalize(handle)
    return volume, hdr, store_hdr
end

function empty_like_minc_volume_std_history(path::String,
                                            ::Type{T}=Float32) where T<:Number
    handle = open_minc_file(path)
    volume, hdr, store_hdr = empty_like_minc_volume_std(handle, T)
    history = read_history(handle)
    close_minc_file(handle)
    finalize(handle)
    return volume, hdr, store_hdr, history
end

function read_minc_volume_std(path::String,
        ::Type{T}=Float32)::Tuple{Array{T},MincHeader,MincHeader} where T<:Number
    handle = open_minc_file(path)
    volume, hdr, store_hdr = read_minc_volume_std(handle, T)
    close_minc_file(handle)
    finalize(handle)
    return volume, hdr, store_hdr
end


function read_minc_volume_std_history(path::String,
        ::Type{T}=Float32)::Tuple{Array{T},MincHeader,MincHeader,Union{String,Nothing}} where T<:Number
    handle = open_minc_file(path)
    volume, hdr, store_hdr = read_minc_volume_std(handle, T)
    history = read_history(handle)
    close_minc_file(handle)
    finalize(handle)
    return volume, hdr, store_hdr, history
end


function empty_like_minc_volume_raw(path::String,
        ::Type{T}=Float32)::Tuple{Array{T},MincHeader} where T<:Number
    handle = open_minc_file(path)
    volume, store_hdr = empty_like_minc_volume_raw(handle, T)
    close_minc_file(handle)
    finalize(handle)
    return volume, store_hdr
end

function read_minc_volume_raw(path::String,
        ::Type{T}=Float32)::Tuple{Array{T},MincHeader} where T<:Number
    handle = open_minc_file(path)
    volume, store_hdr = read_minc_volume_raw(handle, T)
    close_minc_file(handle)
    finalize(handle)
    return volume, store_hdr
end

function read_minc_volume_raw_history(path::String,
        ::Type{T}=Float32) where T<:Number
    handle = open_minc_file(path)
    volume, store_hdr = read_minc_volume_raw(handle, T)
    history = read_history(handle)
    close_minc_file(handle)
    finalize(handle)
    return volume, store_hdr, history
end

# -------------------- Writing volumes --------------------

function write_minc_volume_raw(h::VolumeHandle, volume::Array{T}) where T<:Number
    @minc2_check minc2_save_complete_volume(
        h.x, Base.unsafe_convert(Ptr{Cvoid}, volume), julia_to_minc2[Type{T}])
    return nothing
end

function write_minc_volume_std(h::VolumeHandle, volume::Array{T}) where T<:Number
    setup_standard_order(h)
    write_minc_volume_raw(h, volume)
    return nothing
end

function copy_minc_metadata(i::VolumeHandle, o::VolumeHandle)
    @minc2_check minc2_copy_metadata(i.x, o.x)
    return nothing
end

# arbitrary variables reading and writing
function read_variable(h::VolumeHandle, path::String, name::String) ::Union{AbstractVector,Nothing}
    var_type   = Ref{Cint}(0)
    ndims      = Ref{Cint}(0)

    @minc2_check Minc2.minc2_get_variable_ndims(h.x, path, name, ndims)

    dims = Vector{Cint}(undef, ndims[])
    @minc2_check Minc2.minc2_get_variable_dims(h.x, path, name, dims)

    var_type = Ref{Cint}(0)
    @minc2_check Minc2.minc2_get_variable_type(h.x, path, name, var_type)

    # @minc2_check minc2_read_variable(
    #     h.x, name, Base.unsafe_convert(Ptr{Cvoid}, data), length(data), julia_to_minc2[Type{T}])
    # return nothing
    start = zeros(Cint, ndims[])

    if var_type[] == MINC2_FLOAT
        buf = Array{Float32}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{Float32}], start , dims, buf)
        return buf
    elseif var_type[] == MINC2_DOUBLE
        buf = Array{Float64}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{Float64}], start , dims, buf)
        return buf
    elseif var_type[] == MINC2_INT
        buf = Array{Int32}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{Int32}], start , dims, buf)
        return buf
    elseif var_type[] == MINC2_SHORT
        buf = Array{Int16}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{Int16}], start , dims, buf)
        return buf
    elseif var_type[] == MINC2_UINT
        buf = Array{UInt32}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{UInt32}], start , dims, buf)
        return buf
    elseif var_type[] == MINC2_USHORT
        buf = Array{UInt16}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{UInt16}], start , dims, buf)
        return buf
    elseif var_type[] == MINC2_BYTE
        buf = Array{Int8}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{Int8}], start , dims, buf )
        return buf
    elseif var_type[] == MINC2_UBYTE
        buf = Array{UInt8}(undef, (dims...))
        @minc2_check minc2_read_variable_raw(h.x, path, name, julia_to_minc2[Type{UInt8}], start , dims, buf)
        return buf
    else
        throw(SystemError("MINC2 unsupported data type"))
    end
end

function write_variable(h::VolumeHandle, path::String, name::String, data::Vector{T}) where T<:Number
    count = Cint[length(data)]
    start = Cint[0]
    @minc2_check minc2_write_variable_raw(
        h.x, path, name, julia_to_minc2[Type{T}], start, count, data)
    return nothing
end




# -------------------- Attributes and history --------------------

function read_attribute(h::VolumeHandle,
                        group::String,
                        attribute::String)::Union{String,AbstractVector,Nothing}
    attr_type   = Ref{Cint}(0)
    attr_length = Ref{Cint}(0)

    @minc2_check minc2_get_attribute_type(h.x, group, attribute, attr_type)
    @minc2_check minc2_get_attribute_length(h.x, group, attribute, attr_length)

    len = attr_length[]

    if attr_type[] == MINC2_STRING
        buf = Vector{UInt8}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return String(buf)
    elseif attr_type[] == MINC2_FLOAT
        buf = Vector{Float32}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    elseif attr_type[] == MINC2_DOUBLE
        buf = Vector{Float64}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    elseif attr_type[] == MINC2_INT
        buf = Vector{Int32}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    elseif attr_type[] == MINC2_SHORT
        buf = Vector{Int16}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    elseif attr_type[] == MINC2_UINT
        buf = Vector{UInt32}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    elseif attr_type[] == MINC2_USHORT
        buf = Vector{UInt16}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    elseif attr_type[] == MINC2_BYTE
        buf = Vector{Int8}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    elseif attr_type[] == MINC2_UBYTE
        buf = Vector{UInt8}(undef, len)
        @minc2_check minc2_read_attribute(h.x, group, attribute, buf, len)
        return buf
    else
        throw(SystemError("MINC2 unsupported data type"))
    end
end

function get_attribute(h::VolumeHandle, g::String, a::String; default=missing)
    r = default
    if g == ""
        try
            r = read_attribute(h, g, a)
        catch err
            if !isa(err, Minc2Error)
                rethrow(err)
            end
        end
    elseif g in groups(h)
        if a in attributes(h, g)
            r = read_attribute(h, g, a)
        end
    end

    if !ismissing(r)
        if r isa AbstractVector{<:Number} && length(r) == 1
            r = r[1]
        end
        if r isa String
            r = rstrip(r, '\0')
        end
    end
    return r
end

function groups(h::VolumeHandle)
    it = minc2_allocate_info_iterator()
    r  = String[]
    try
        @minc2_check minc2_start_group_iterator(h.x, it)
        while minc2_iterator_group_next(it) == MINC2_SUCCESS
            push!(r, unsafe_string(minc2_iterator_group_name(it)))
        end
    finally
        @minc2_check minc2_free_info_iterator(it)
    end
    return r
end

function attributes(h::VolumeHandle, g::String)
    it = minc2_allocate_info_iterator()
    r  = String[]
    try
        @minc2_check minc2_start_attribute_iterator(h.x, g, it)
        while minc2_iterator_attribute_next(it) == MINC2_SUCCESS
            push!(r, unsafe_string(minc2_iterator_attribute_name(it)))
        end
    finally
        @minc2_check minc2_free_info_iterator(it)
    end
    return r
end

function write_attribute(h::VolumeHandle,
                         group::String,
                         attribute::String,
                         value::T) where T
    val_type = julia_to_minc2[Type{T}]
    attr_length = length(value)

    if value isa String
        buf = Vector{UInt8}(value)
        @minc2_check minc2_write_attribute(
            h.x, group, attribute, Base.unsafe_convert(Ptr{Cvoid}, buf), attr_length, val_type)
    else
        @minc2_check minc2_write_attribute(
            h.x, group, attribute, Base.unsafe_convert(Ptr{Cvoid}, value), attr_length, val_type)
    end
    return nothing
end

function read_history(i::VolumeHandle)::Union{String,Nothing}
    return get_attribute(i, "", "history", default=nothing)
end

function write_history(i::VolumeHandle, history::String)
    write_attribute(i, "", "history", history)
    return nothing
end

# -------------------- World/voxel transforms --------------------
function world_to_voxel(h::VolumeHandle, xyz::Vector{Float64})::Vector{Float64}
    @assert length(xyz) == 3
    ijk = zeros(Float64, 3)
    @minc2_check minc2_world_to_voxel(h.x, xyz, ijk)
    return ijk
end

function voxel_to_world(h::VolumeHandle, ijk::Vector{Float64})::Vector{Float64}
    @assert length(ijk) == 3
    xyz = zeros(Float64, 3)
    @minc2_check minc2_voxel_to_world(h.x, ijk, xyz)
    return xyz
end

function voxel_to_world(hdr::MincHeader)::AffineTransform{Float64}
    rot    = zeros(3,3)
    scales = zeros(3,3)
    start  = zeros(3)

    for i = 1:3
        aa = findfirst(isequal(DIM(i)), hdr.axis)
        if hdr.dir_cos_valid[aa]
            rot[1:3, i] = hdr.dir_cos[aa, 1:3]
        else
            rot[i, i] = 1
        end
        scales[i, i] = hdr.step[aa]
        start[i]     = hdr.start[aa]
    end
    origin = rot * start
    return AffineTransform(rot * scales, origin)
end

function world_to_voxel(hdr::MincHeader)::AffineTransform{Float64}
    return inv(voxel_to_world(hdr))
end

function create_header_from_v2w(sz,
                                t::AffineTransform{T};
                                vector_dim::Bool=false,
                                time_dim::Bool=false,
                                time_step::Union{Float64,Nothing}=nothing,
                                time_start::Union{Float64,Nothing}=nothing,
                                time_coords::Union{Vector{Float64},Nothing}=nothing,
                                time_widths::Union{Vector{Float64},Nothing}=nothing,
                                irregular_time::Bool=false)::MincHeader where T
    start, step, dir_cos = decompose(t)

    hdr = MincHeader(3 + vector_dim + time_dim)

    if time_dim && !isnothing(time_coords)  && length(time_coords) != sz[4 + vector_dim ]
        @error "Unexpected length of time coordinates: $(length(time_coords)) != $(sz[4 + vector_dim ])"
    end

    for i = 1:length(sz)
        hdr.dims[i] = sz[i]
        if vector_dim && i == 1 # Vector dimension is the first dimension if present
            hdr.start[i] = 0
            hdr.step[i]  = 1.0
            hdr.dir_cos_valid[i] = false
            hdr.dir_cos[i, :] .= 0.0
            hdr.axis[i] = DIM_VEC
        elseif time_dim && (i - vector_dim) == 4 # Time dimension is the 4th dimension after vector dim
            hdr.axis[i]  = DIM_TIME
            hdr.irregular[i] = irregular_time

            if !isnothing(time_coords) 
                hdr.offsets[i] = copy(time_coords)
                hdr.widths[i] = !isnothing(time_widths) ? copy(time_widths) : fill(1.0, sz[i])
                hdr.start[i] = time_coords[1]

                hdr.step[i]  = length(time_coords) > 1 ?
                    (time_coords[end] - time_coords[1]) / (length(time_coords) - 1) :
                    1.0
            else
                hdr.step[i]  = isnothing(time_step) ? 1.0 : time_step
                hdr.start[i] = isnothing(time_start) ? 0.0 : time_start
            end
        else
            hdr.start[i] = start[i - vector_dim]
            hdr.step[i]  = step[i - vector_dim]
            hdr.dir_cos[i, :] .= dir_cos[:, i - vector_dim]
            hdr.dir_cos_valid[i] = true
            hdr.axis[i] = DIM(i - vector_dim)
        end
    end
    return hdr
end

# -------------------- High-level writers --------------------

function write_minc_volume_std(path::String, ::Type{Store},
                               store_hdr::Union{MincHeader,Nothing},
                               volume::Array{Repr};
                               like::Union{String,Nothing}=nothing,
                               history::Union{String,Nothing}=nothing) where {Store,Repr}
    if isnothing(like)
        handle = define_minc_file(store_hdr, Store, Repr)
        create_minc_file(handle, path)
        if !isnothing(history)
            write_history(handle, history)
        end
        write_minc_volume_std(handle, volume)
        close_minc_file(handle)
        finalize(handle)
    else
        in_h = open_minc_file(like)
        store_hdr2 = store_header(in_h)
        handle = define_minc_file(store_hdr2, Store, Repr)
        create_minc_file(handle, path)
        copy_minc_metadata(in_h, handle)
        if !isnothing(history)
            write_history(handle, history)
        end
        write_minc_volume_std(handle, volume)
        close_minc_file(in_h)
        close_minc_file(handle)
        finalize(handle)
    end
    return nothing
end


function extract_time_info(store_hdr::MincHeader)
    time_idx = findfirst(==(DIM_TIME), store_hdr.axis)
    if time_idx === nothing
        return Float64[0.0], Float64[1.0], false
    elseif store_hdr.irregular[time_idx]
        return store_hdr.offsets[time_idx], store_hdr.widths[time_idx], true
    else
        n = store_hdr.dims[time_idx]
        start = store_hdr.start[time_idx]
        step = store_hdr.step[time_idx]
        time_coords = [start + (i-1)*step for i in 1:n]
        time_widths = fill(step, n)
        return time_coords, time_widths, false
    end
end


function write_minc_volume_raw(path::String, ::Type{Store},
                               store_hdr::Union{MincHeader,Nothing},
                               volume::Array{Repr};
                               like::Union{String,Nothing}=nothing,
                               history::Union{String,Nothing}=nothing) where {Store,Repr}
    if isnothing(like)
        handle = define_minc_file(store_hdr, Store, Repr)
        create_minc_file(handle, path)
        if !isnothing(history)
            write_history(handle, history)
        end
        write_minc_volume_raw(handle, volume)
        close_minc_file(handle)
        finalize(handle)
    else
        in_h = open_minc_file(like)
        store_hdr2 = store_header(in_h)
        handle = define_minc_file(store_hdr2, Store, Repr)
        create_minc_file(handle, path)
        copy_minc_metadata(in_h, handle)
        if !isnothing(history)
            write_history(handle, history)
        end
        write_minc_volume_raw(handle, volume)
        close_minc_file(in_h)
        close_minc_file(handle)
        finalize(handle)
    end
    return nothing
end

#end # module
